DECLARE @USER VARCHAR(30)
SET @USER = ' Thiago Farias '

SELECT @USER AS NAME

SELECT
	@USER,
	LEN(@USER),
	RTRIM(@USER),
	LTRIM(@USER),
	TRIM(@USER),
	UPPER(TRIM(@USER)),
	LOWER(TRIM(@USER)),
	UPPER(LOWER(TRIM(@USER)))