USE PRIMEIRO_BD

UPDATE CLIENTES
SET EMAIL = 'CONTATO@BRUCE.COM.BR'
WHERE ID_CLIENTE = 1

UPDATE CLIENTES
SET NOME = 'BRUCE FONSECA 2',
	EMAIL = 'BRUCEFONSECA2@BRUCE.COM.BR'
WHERE
	ID_CLIENTE = 2

SELECT * FROM CLIENTES