USE ContosoRetailDW

-- END OF MONTH
SELECT EOMONTH(GETDATE())

-- ADICIONANDO 01 MÊS
SELECT
	GETDATE(),
	EOMONTH(GETDATE()), -- END OF MONTH
	EOMONTH(GETDATE(), 1), --ADICIONANDO UM MÊS
	EOMONTH(GETDATE(), -1) --SUBTRAINDO UM MÊS