USE ContosoRetailDW

--- SUBQUERRY / SUB CONSULTA

SELECT
	AVG(SQ.VENDAS)
FROM(
	SELECT
		DATEPART(YEAR ,S.DateKey) AS ANO,
		DATEPART(MONTH ,S.DateKey) AS MÊS,
		SUM(S.SalesAmount) AS VENDAS
	FROM FactSales AS S
	GROUP BY DATEPART(YEAR ,S.DateKey), DATEPART(MONTH ,S.DateKey)
) AS SQ

--- CTE - COMMON TABLE EXPRESSION

WITH SALES_MONTH_AVG(ANO, MÊS, VENDAS)
AS
(
	SELECT
		DATEPART(YEAR ,S.DateKey) AS ANO,
		DATEPART(MONTH ,S.DateKey) AS MÊS,
		SUM(S.SalesAmount) AS VENDAS
	FROM FactSales AS S
	GROUP BY DATEPART(YEAR ,S.DateKey), DATEPART(MONTH ,S.DateKey)
)
SELECT
	AVG(SALES_MONTH_AVG.VENDAS) MEDIA_MENSAL
FROM SALES_MONTH_AVG